import { Database } from './database.types'

// Re-export specific Row types for all 43 tables
export type AdminAction = Database['public']['Tables']['admin_actions']['Row']
export type AnalyticsDaily = Database['public']['Tables']['analytics_daily']['Row']
export type AuditLog = Database['public']['Tables']['audit_logs']['Row']
export type BookingItem = Database['public']['Tables']['booking_items']['Row']
export type Booking = Database['public']['Tables']['bookings']['Row']
export type Category = Database['public']['Tables']['categories']['Row']
export type Conversation = Database['public']['Tables']['conversations']['Row']
export type DiscussionLike = Database['public']['Tables']['discussion_likes']['Row']
export type EventAgenda = Database['public']['Tables']['event_agenda']['Row']
export type EventCohost = Database['public']['Tables']['event_cohosts']['Row']
export type EventDiscussion = Database['public']['Tables']['event_discussions']['Row']
export type EventFaq = Database['public']['Tables']['event_faqs']['Row']
export type EventImage = Database['public']['Tables']['event_images']['Row']
export type EventInterest = Database['public']['Tables']['event_interests']['Row']
export type EventLike = Database['public']['Tables']['event_likes']['Row']
export type EventReview = Database['public']['Tables']['event_reviews']['Row']
export type EventSave = Database['public']['Tables']['event_saves']['Row']
export type EventTag = Database['public']['Tables']['event_tags']['Row']
export type EventWaitlist = Database['public']['Tables']['event_waitlist']['Row']
export type Event = Database['public']['Tables']['events']['Row']
export type FeaturedSlot = Database['public']['Tables']['featured_slots']['Row']
export type HostFollow = Database['public']['Tables']['host_follows']['Row']
export type HostProfile = Database['public']['Tables']['host_profiles']['Row']
export type Location = Database['public']['Tables']['locations']['Row']
export type Message = Database['public']['Tables']['messages']['Row']
export type NotificationTemplate = Database['public']['Tables']['notification_templates']['Row']
export type Notification = Database['public']['Tables']['notifications']['Row']
export type Payout = Database['public']['Tables']['payouts']['Row']
export type PlatformConfig = Database['public']['Tables']['platform_config']['Row']
export type PromoCodeUse = Database['public']['Tables']['promo_code_uses']['Row']
export type PromoCode = Database['public']['Tables']['promo_codes']['Row']
export type Report = Database['public']['Tables']['reports']['Row']
export type ReviewHelpfulVote = Database['public']['Tables']['review_helpful_votes']['Row']
export type SavedSearch = Database['public']['Tables']['saved_searches']['Row']
export type Tag = Database['public']['Tables']['tags']['Row']
export type TicketTier = Database['public']['Tables']['ticket_tiers']['Row']
export type Ticket = Database['public']['Tables']['tickets']['Row']
export type UserBlock = Database['public']['Tables']['user_blocks']['Row']
export type UserOauthAccount = Database['public']['Tables']['user_oauth_accounts']['Row']
export type UserSession = Database['public']['Tables']['user_sessions']['Row']
export type UserToken = Database['public']['Tables']['user_tokens']['Row']
export type User = Database['public']['Tables']['users']['Row']
export type VTicketAvailability = Database['public']['Views']['v_ticket_availability']['Row']
export type VEventsPublic = Database['public']['Views']['v_events_public']['Row']

// Insert variants for top 10 most used tables
export type UserInsert = Database['public']['Tables']['users']['Insert']
export type EventInsert = Database['public']['Tables']['events']['Insert']
export type BookingInsert = Database['public']['Tables']['bookings']['Insert']
export type TicketTierInsert = Database['public']['Tables']['ticket_tiers']['Insert']
export type HostProfileInsert = Database['public']['Tables']['host_profiles']['Insert']
export type MessageInsert = Database['public']['Tables']['messages']['Insert']
export type ConversationInsert = Database['public']['Tables']['conversations']['Insert']
export type EventReviewInsert = Database['public']['Tables']['event_reviews']['Insert']
export type EventDiscussionInsert = Database['public']['Tables']['event_discussions']['Insert']
export type NotificationInsert = Database['public']['Tables']['notifications']['Insert']

// Update variants for top 10 most used tables
export type UserUpdate = Database['public']['Tables']['users']['Update']
export type EventUpdate = Database['public']['Tables']['events']['Update']
export type BookingUpdate = Database['public']['Tables']['bookings']['Update']
export type TicketTierUpdate = Database['public']['Tables']['ticket_tiers']['Update']
export type HostProfileUpdate = Database['public']['Tables']['host_profiles']['Update']
export type MessageUpdate = Database['public']['Tables']['messages']['Update']
export type ConversationUpdate = Database['public']['Tables']['conversations']['Update']
export type EventReviewUpdate = Database['public']['Tables']['event_reviews']['Update']
export type EventDiscussionUpdate = Database['public']['Tables']['event_discussions']['Update']
export type NotificationUpdate = Database['public']['Tables']['notifications']['Update']
